//data
export const SET_SEARCH_RESULT_MOVIES = 'SET_SEARCH_RESULT_MOVIES';
export const SET_SEARCH_RESULT_TYPE = 'SET_SEARCH_RESULT_TYPE';
export const SET_SEARCH_RESULT_WORD = 'SET_SEARCH_RESULT_WORD';

//UI
export const LOADING_UI = 'LOADING_UI';
export const UNLOADING_UI = 'UNLOADING_UI';
export const SET_ERRORS = 'SET_ERRORS';
